Add test data interaction
trushkin-ilya/face-anti-spoofer pull request #23
Opened 2020-02-19 19:30 UTC by trushkin-ilya

2020-02-19 19:31 UTC, trushkin-ilya commented
@grib0ed0v, requesting a review.

2020-02-25 07:29 UTC, grib0ed0v commented on datasets.py
> +            if mode != 'test':
if self.mode would be better,

2020-02-25 07:35 UTC, grib0ed0v requested changes

2020-02-25 07:35 UTC, grib0ed0v commented on submit.py
> +            dataloader = data.DataLoader(dataset, batch_size=args.batch_size)
How about adding num_workers to DataLoader?

2020-02-25 07:35 UTC, grib0ed0v commented on test.py
> +    dataloader = data.DataLoader(dataset, batch_size=args.batch_size)
num_workers?

2020-02-26 06:58 UTC, merged